language: python
python:
  - '2.7'
cache: pip
install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install --no-cache-dir --editable .
script:
  - python setup.py test
deploy:
  provider: pypi
  user: michael.shaffer
  on:
    tags: true

