language: python
python:
- '2.7'
cache: pip
before_install:
- pip install --upgrade pip
- pip install pytest pytest-cov
- pip install coveralls
install:
- pip install --no-cache-dir --editable .
script:
- py.test --cov SCNIC --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: pypi
  user: michael.shaffer
  password:
    secure: eJ2ci1xIvRbCRWPug7FVWIJkZ5qMemTOweX15msUcNF7m8KZG328eM8Z+FoL+xJ+NjqxjFLe+l5akSxHd2EHk80swcRLvCuZq/42deOSJxEi3cnfjInNJRSeOrfBFyWXhQC1L9wSjKc0zNv9/wf1rwC1dWrh1VqAO6i/pYShN117KlvXJhE2tnuJZyK4fJiDNrSlNR26n/2nuA7Y2/sr3w/qttdg19tmvj0BThYy/ufxKwBPoGebhYfZKQgOIwwgfBGH2a5035Njjc7gFlatqsgzc8Amm0mILD+iCVNYb87p391z+cks5ZZm+sELOm5dc+MeT56L9dqZyARGVV1QmB8KY9C2xe1jPA8UF4OYg6cl0AkaSAE9PNPs+oUothnq14Cf6wEq0tezz8yO6dWn/Xmx2inHgZ8UYFn7Je4QRt4kBzZKQztr9L9QXCwRseD8ApsJl9Q2XC7ucrW+G7WJ1IydtOxZWgnblZrdOdd0+ycE/bfv1r9mkLWyc256/Ik8qZbC+XqBCWxf1iK6sExevwftgR+dF/FWgeHnUnkJ2ISEygat+GjPY0yzn1+l7VTIEAPa09EiY1hahlctNViWHudS7VaKOJKV/JPEoTllpZWZ/jJN22x0pVqB4WRWiXD8k5iNOQuLiMBaThVacfSWZSWysm8PAzAQtYEvkUouy1I=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: shafferm/SCNIC
